#!/bin/bash
if test -d /etc/nginx/sites-available && test -d /etc/nginx/sites-enabled  ; then
    echo "-------------------------------"
else
    echo "Error!! Folders /etc/nginx/sites-available & etc/nginx/sites-enabled not found."
    exit 0
fi

avail=/etc/nginx/sites-enabled/$1.conf
enabled=/etc/nginx/sites-enabled
site=`ls /etc/nginx/sites-enabled`

if [ "$#" != "1" ]; then
    echo "Use script: n2dissite site_config"
    echo -e "\nEnabled configs: \n$site"
    exit 0
else
    if test -e $avail; then
	rm  $avail
    else
	echo -e "$avail config does not exist! Exiting"
	exit 0
    fi
    if test -e $enabled/$1.conf; then
	echo "Error!! Could not remove $avail config!"
    else
	echo  -e "Success! $avail has been removed!\nsudo systemctl reload nginx"
        exit 0
    fi
fi
