#!/bin/bash

ng_fld_s_av=/etc/nginx/sites-available
ng_fld_s_en=/etc/nginx/sites-enabled

# pipe + args
pp1=();pp1+=("$@")
read -r -t .01 -a pp2
pp1+=("${pp2[@]}")

[ "${#pp1[*]}" = "0" ] && {
  echo "Use script: n2ensite site_config1 site_config2 ..."
  exit 1
}
if test -d $ng_fld_s_av && test -d $ng_fld_s_en; then
  echo "-------------------------------"
else
  echo "Error. Folders ${ng_fld_s_av} or(and) ${ng_fld_s_en} not found"
  exit 1
fi

is_restart_nginx=0 # флаг, требуется ли перезагрузить nginx.service
num_all=0
num_success=0
for i in "${pp1[@]}"; do
  #echo "$i"
  if [[ "${i: -5}" != '.conf' ]]; then
    current_conf="${i}.conf"
  else
    current_conf="${i}"
  fi
  while IFS= read -r -d '' file
  do
    num_all=$((num_all+1))
    rm "$file"
    echo "Disable sites in file conf: $file"
    num_success=$((num_success+1))
    is_restart_nginx=1
  done <  <(find "$ng_fld_s_en" -name "$current_conf" \( -type l -or -type f \) -print0)
done
# завершение и вывод предупреждающих сообщений
if [ "$is_restart_nginx" != "0" ]; then
  echo "All conf files: $num_all"
  echo "Success: $num_success"
  echo "For test nginx config: sudo nginx -t"
  echo "Now reload nginx server: sudo systemctl reload nginx"
fi
