#!/bin/bash
# use n2ensite s1.conf s2 s3
ng_fld_s_av=/etc/nginx/sites-available
ng_fld_s_en=/etc/nginx/sites-enabled

if test -d $ng_fld_s_av && test -d $ng_fld_s_en; then
  echo "-------------------------------"
else
  echo "Error. Folders ${ng_fld_s_av} or(and) ${ng_fld_s_en} not found"
  exit 1
fi

[ -z $1 ] && {
  echo "Use script: n2ensite site_config1 site_config2 ..."
  exit 1
}

cp=$#
for i in $@; do
  if [[ "${i: -5}" != '.conf' ]]; then
    current_conf="${i}.conf"
  else
    current_conf="${i}"
  fi
  echo $current_conf
  
done


exit


avail=/etc/nginx/sites-available/$1.conf
enabled=/etc/nginx/sites-enabled

site=`ls /etc/nginx/sites-available/`

if [ "$#" != "1" ]; then
  echo "Use script: n2ensite site_config1 site_config2 ..."
  echo -e "\nAvailable configs:\n$site"
  exit 0
else
  if test -e $avail; then
    ln -s $avail $enabled
  else
    echo -e "$avail config does not exist! Please create one!\n$site"
    exit 0
  fi
  if test -e $enabled/$1.conf; then
    echo "Success!!"
    echo "For test nginx config: sudo nginx -t"
    echo "Now reload nginx server: sudo systemctl reload nginx"
  else
    #echo  -e "Config $avail does not exist!\nPlease see avail configs:\n$site"
    exit 0
  fi
fi
